### ISSUE TITLE
Documentation for rust-protobuf [NotAnIssue]

### ISSUE THREAD

**Issue by igiona** [jgarzik/rust-protobuf-example#11]
Hi @jgarzik , thank you for building this example, it's laterally the only "end-to-end" example of the rust-protobuf I could find.
On the other hand, it has been "hard" to spot...

The maintainer of [rust-protobuf](https://github.com/stepancheg/rust-protobuf/tree/master) is seeking for help, among others for examples and documentation.

Why don't you propose your work here on it's repo?
I'm sure people will appreciate your contribution there 👍 

Cheers!

**Comment by jgarzik** [comment]
Opened a PR: https://github.com/stepancheg/rust-protobuf/pull/713
