### ISSUE TITLE
Curious about `set_name`, `set_age`, etc.

### ISSUE THREAD

**Issue by willricketts** [jgarzik/rust-protobuf-example#2]
Greetings!

I'm a bit new to Rust, so bare with me if this is a bit of a noobish question. Taking a look at `main.rs`, I noticed calls to `out_msg.set_name` and `out_msg.set_age` and I'm not entirely sure of where they come from:

https://github.com/jgarzik/rust-protobuf-example/blob/e138247a2fab96bc68d13ac0e599ae2844523fd2/src/main.rs#L9-L10

Are these automatically generated? I'm not seeing definitions for them anywhere.

Thanks!

**Comment by jgarzik** [comment]
Yes, automatically generated.
